name: Test
on:
  push:
    branches:
      - "test-*"
jobs:
  gvm-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v3   

    # Sets up node
    - name: 🧰 Setup node
      uses: actions/setup-node@v1
      with:
          node-version: 16

    - name: 🔧 Npm install
      run: npm ci

    # Runs gulp to build
    - name: 🏗️ Build with gulp
      run: gulp

    - name: 📩 Deploy to custom domain
      uses: SamKirkland/FTP-Deploy-Action@4.3.1
      with:
        server: taj.greenvisionmedia.net  
        username: taj@greenvisionmedia.net
        password: ${{secrets.FTP_PASSWORD}}
        server-dir: taj.greenvisionmedia.net/public_html/
        local-dir: public/
        protocol: ftps
