name: Test
on:
  push:
    branches:
      - "test-*"
  workflow_dispatch:
jobs:
  gvm-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4   

    # Dockerfile fix with cwebp a la https://github.com/imagemin/cwebp-bin/issues/31
    - name: 😐 Docker fix
      run: apt-get update && apt-get install -y libglu1

    # Sets up node
    - name: 🧰 Setup node
      uses: actions/setup-node@v4
      with:
          node-version: 22

    - name: 🔧 Npm install
      run: npm ci

    # Runs gulp to build
    - name: 🏗️ Build with gulp
      run: npx gulp

    - name: 📩 Deploy to custom domain
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: taj.greenvisionmedia.net  
        username: taj@greenvisionmedia.net
        password: ${{secrets.TEST_PASSWORD}}
        server-dir: taj.greenvisionmedia.net/public_html/
        local-dir: public/
